# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDLogDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDLogDemo

  target 'DDLogDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DDLogDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end


  pod 'CocoaLumberjack/Swift'





end
